### ISSUE TITLE
Whatsapp could not show the preview page on the blog post

### ISSUE THREAD

**Issue by winstonma** [datocms/gatsby-blog-demo#4]
I attached the screenshot for whatsapp sharing with the following link

- https://datocms-gatsby-blog-demo.netlify.app/
- https://datocms-gatsby-blog-demo.netlify.app/posts/spicy-jalapeno-bacon
- https://www.espn.com/nfl/insider/story/_/id/32433617/nfl-trade-deadline-proposals-imagining-10-offers-players-including-xavien-howard-jabrill-peppers

![image](https://user-images.githubusercontent.com/1215090/138308818-4540ee62-0629-41dc-b997-75060f68c22d.png)

As the screenshot shown, all three links show different preview in Whatspp. What I would expect is the second link shows the same kind of screenshot as the third one. Would it be possible? Thanks

**Comment by matjack1** [comment]
Hey @winstonma have you tried populating the SEO field in the record to set the OG image?

You can probably also set the fallback image on the project level and see if that shows for the homepage. I think it should work!

**Comment by winstonma** [comment]
Hi @matjack1 I checked that the [deployed page](https://datocms-gatsby-blog-demo.netlify.app/posts/spicy-jalapeno-bacon) have the field `og:image`.

In addition I checked the page against [Twitter Card Validator](https://cards-dev.twitter.com/validator) and [Facebook share](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdatocms-gatsby-blog-demo.netlify.app%2Fposts%2Fspicy-jalapeno-bacon) with no error. So honestly I have no idea what is missing.

It is very frustrating when there is no Whatsapp sharing debugger to check, telling me what's wrong.

**Comment by marcelofinamorvieira** [comment]
Hello @winstonma,  i've tried to reproduce the behavior you sent, but with no success.
I got the expected preview images for all posts in the blog:
![image](https://user-images.githubusercontent.com/44898680/141306667-2e790898-ef4e-4ccb-be39-228f88440a24.png)
Maybe you had a temporary network issue?
Could you try to wait a couple of seconds before sending the link after typing it on Whatsapp, and see if it loads the preview?

Let me know if it works

**Comment by winstonma** [comment]
Thanks @marcelofinamorvieira. As I mentioned before the page works on all facebook and twitter. Only whatsapp (maybe just my whatsapp) doesn't show the preview. Also I would be frustrating when there is no whatsapp debugger tool to tell me what is missing.

I will check this with my friend's whatsapp account and get back to you.

**Comment by matjack1** [comment]
I'm closing this for now, but feel free to reopen if you find anything useful!
